//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularDatagrid.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel
    {
        public int Id { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string TcNo { get; set; }
        public string Unvan { get; set; }
        public string Departman { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
    }
}
